apiVersion: v1
kind: Namespace
metadata:
  name: wandb-launch-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: launch-agent-demo
  namespace: wandb-launch-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launch-agent-demo
  template:
    metadata:
      labels:
        app: launch-agent-demo
    spec:
      securityContext:
        fsGroup: 107    # Group ID of docker group on k8s nodes. Also 412
      containers:
      - name: launch-agent-demo
        image: launch-agent-container:v0
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: WANDB_PROJECT
          valueFrom:
            configMapKeyRef:
              name: wandb-setup
              key: wandb-project
        - name: WANDB_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: wandb-setup
              key: wandb-base-url
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-api-key
              key: password
        securityContext:
          privileged: true
          runAsNonRoot: false # added
          runAsUser: 0
          capabilities: 
            drop:
              - all
          allowPrivilegeEscalation: true
        volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
        # - name: wandb-dir
        #   mountPath: "/root/wandb"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      # - name: wandb-dir
      #   hostPath:
      #     path: /Users/kyle/newcli/client
      - name: wandb-setup
        configMap:
          name: wandb-setup
---
apiVersion: v1
data:
  wandb-base-url: "https://api.wandb.ai" ### base url here
  wandb-project: "launch_demo"
kind: ConfigMap
metadata:
  name: wandb-setup
  namespace: wandb-launch-agent
---
apiVersion: v1
kind: Secret
metadata:
  name: wandb-api-key
  namespace: wandb-launch-agent
type: kubernetes.io/basic-auth
stringData:
  password: ""  ### API KEY HERE